# paper trading

dev:
  logging_level: DEBUG
  logging_file: "dev.log"

ib:
  ip: localhost
  port: 7497
  clientId: 0

alpaca:
  url: "https://paper-api.alpaca.markets"

data:
  base_folder: "goquantdata"
  csv_folder: "raw_data_dev"
