# paper trading

dev:
  logging-level: DEBUG

ib:
  ip: localhost
  port: 7497
  clientId: 0

alpaca:
  url: "https://paper-api.alpaca.markets"
  id: "test"
  key: "test"

binance:
  key: ""
  secret: ""

data:
  base_folder: "goquantdata"
  csv_folder: "raw_data_test"
