# paper trading

dev:
  logging-level: DEBUG

ib:
  ip: localhost
  port: 7497
  clientId: 0

alpaca:
  url: "https://paper-api.alpaca.markets"
  # empty test account for paper trading
  id: "PKNYZ3YUDGKRRW4WFUKB"
  key: "5h7eoROgFCtLDheOGrKGKOREIDGWVtKnWKcTM3l8"

binance:
  key: ""
  secret: ""

data:
  base_folder: "goquantdata"
  csv_folder: "raw_data_test"
